import type { NextPage } from 'next'
import { useCallback, useEffect } from 'react'
import Head from 'next/head'
import useTranslation from 'next-translate/useTranslation'

import { useFeatureToggle } from '../hooks/useFeatureToggle'
import { FeatureArray, fetchFeatures } from '../services/FeatureToggle'

const Home: NextPage = () => {
  const { t } = useTranslation('common')
  const [isEnabled, enableFeature, disableFeature] = useFeatureToggle()

  const processFeatures = useCallback(async () => {
    try {
      const features = await fetchFeatures()

      console.log('FEATURES: ', features)

      features.forEach(([featureName, isEnabled]: FeatureArray) =>
        isEnabled ? enableFeature(featureName) : disableFeature(featureName),
      )
    } catch {
      // do nothing
    }
  }, [enableFeature, disableFeature])

  useEffect(() => {
    processFeatures()
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{t('title')}</div>
      {isEnabled('sample') && <h1>FEATURE TOGGLE</h1>}
    </>
  )
}

export default Home
